version: '3.8'
services:
  db-alphine:
    stdin_open: true
    tty: true
    build:
      context: ./slony
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nAd4pat0
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata: